### ISSUE TITLE
Exception when assigning Drawable

### ISSUE THREAD

**Issue by Cheesebaron** [garuma/xamsvg#2]
Hi there,

just testing out the library, but I get the following Exception when doing:

```
var bksvLogo = view.FindViewById<ImageView>(Resource.Id.bksvImageView);
using(var drawable = SvgFactory.GetDrawable(Activity.Resources, Resource.Raw.bk_logo))
    bksvLogo.SetImageDrawable(drawable);
```

```
    <ImageView
        android:id="@+id/bksvImageView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_alignParentTop="true"
        android:scaleType="fitXY" />
```

I am certain that the `Resource.Raw.bk_logo` is an SVG, and it opens fine in Inkscape, GIMP and browsers.

```
09-19 14:59:58.510 I/MonoDroid(31854): UNHANDLED EXCEPTION:
09-19 14:59:58.570 I/MonoDroid(31854): System.NotSupportedException: Unable to activate instance of type XamSvg.PictureBitmapDrawable from native handle 9f100019 ---> System.MissingMethodException: No constructor found for XamSvg.PictureBitmapDrawable::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
09-19 14:59:58.570 I/MonoDroid(31854): Java.Lang.Error: Exception of type 'Java.Lang.Error' was thrown.
09-19 14:59:58.570 I/MonoDroid(31854):   --- End of managed exception stack trace ---
09-19 14:59:58.570 I/MonoDroid(31854): java.lang.Error: Java callstack:
09-19 14:59:58.570 I/MonoDroid(31854):  at xamsvg.PictureBitmapDrawable.n_onBoundsChange(Native Method)
09-19 14:59:58.570 I/MonoDroid(31854):  at xamsvg.PictureBitmapDrawable.onBoundsChange(PictureBitmapDrawable.java:59)
09-19 14:59:58.570 I/MonoDroid(31854):  at android.graphics.drawable.Drawable.setBounds(Drawable.java:149)
09-19 14:59:58.570 I/MonoDroid(31854):  at android.widget.ImageView.configureBounds(ImageView.java:872)
09-19 14:59:58.570 I/MonoDroid(31854):  at android.widget.ImageView.setFrame(ImageView.java:850)
09-19 14:59:58.570 I/MonoDroid(31854):  at android.view.View.layout(View.java:14070)
09-19 14:59:58.570 I/MonoDroid(31854):  at android.widget.RelativeLayout.onLayout(RelativeLayout.java:948)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.view.View.layout(View.java:14072)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.view.ViewGroup.layout(ViewGroup.java:4607)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.view.View.layout(View.java:14072)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.view.ViewGroup.layout(ViewGroup.java:4607)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.view.View.layout(View.java:14072)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.view.ViewGroup.layout(ViewGroup.java:4607)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.view.View.layout(View.java:14072)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.view.ViewGroup.layout(ViewGroup.java:4607)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.widget.FrameLayout.onLayout(FrameLayout.java:448)
09-19 14:59:58.575 I/MonoDroid(31854):  at android.view.View.layout(View.java:14072)
```

I am using the latest alpha, haven't tested with anything else.

Microsoft Visual Studio Ultimate 2013
Version 12.0.30723.00 Update 3
Microsoft .NET Framework
Version 4.5.51641

Xamarin   3.6.245.0 (49abddaaec0a8be4cb890b8cddefed81727bbe6c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   4.16.0.17 (2a7b68212b17c903160fbd8e0106babb299d1be3)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.iOS   8.0.52.0 (b38baf1c655f9fe816fee25cbd7ac78225def3e9)
Visual Studio extension to enable development for Xamarin.iOS.

**Comment by Cheesebaron** [comment]
Just added the missing ctor. now `Picture` is `null` when `MakeBitmapFromPicture` is called. Strangeness is occuring!

I am using the Svg stuff inside of a Fragment, but I can't see why that should make a difference.

**Comment by Cheesebaron** [comment]
Removing the `using` statement helped, but `Picture` is still null sometimes, so some checks needed to be introduced. I'll make a pull request.
